name: Run test case

on: [push, pull_request]

jobs:
    run_test_case:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            os:
              - ubuntu20.04
            otp:
              - 24.3.4.2-3
            elixir:
              - 1.13.4
            arch:
              - amd64

        container:
            image: ghcr.io/emqx/emqx-builder/5.0-33:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}

        steps:
        - uses: actions/checkout@v2

        - name: Install prerequisites
          run: |
            apt update
            apt install -y cmake

        - name: Check versions
          run: |
            ./git-tag.sh dummy --dryrun

        - name: Get deps git refs for cache
          id: deps-refs
          run: |
            scripts/get-dep-refs.sh

        - name: load rocksdb cache
          uses: actions/cache@v2
          with:
            path: |
              _build/default/lib/rocksdb/
            key: ${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.arch }}-${{ steps.deps-refs.outputs.DEP_ROCKSDB_REF }}

        - name: Run tests
          run: |
            make eunit
            make ct
            make cover
        - name: Coveralls
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              make coveralls
        - uses: actions/upload-artifact@v1
          if: always()
          with:
            name: logs
            path: _build/test/logs
        - uses: actions/upload-artifact@v1
          with:
            name: cover
            path: _build/test/cover
