name: Run test case

on: [push, pull_request]

jobs:

    run_test_case:

        runs-on: ubuntu-latest

        container:
            image: erlang:24.0

        steps:
        - uses: actions/checkout@v1

        - name: Install prerequisites
          run: |
            apt update
            apt install -y cmake

        - name: Check versions
          run: |
            ./git-tag.sh dummy --dryrun
        - name: Run tests
          run: |
            make eunit
            make ct
            make cover
        - name: Coveralls
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              make coveralls
        - uses: actions/upload-artifact@v1
          if: always()
          with:
            name: logs
            path: _build/test/logs
        - uses: actions/upload-artifact@v1
          with:
            name: cover
            path: _build/test/cover
